[package]
name = "rjplc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
color-eyre = { version = "0.6.3", default-features = false }
enum-iterator = "2.1.0"
nom = "7.1.3"
regex = "1.11.1"

[dev-dependencies]
pretty_assertions = "1.4.1"

[features]
homework = []
default = ["homework"]
