[package]
name = "rjplc-wasm"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
rjplc = { path = "../" }
console_error_panic_hook = "0.1.7"
getrandom = { version = "0.2", features = ["js"] }
