default:
	just --list

build-web:
	wasm-pack build --target web

move-web: build-web
	rm -rf ../../portfolio/rjplc-wasm
	cp -r pkg ../../portfolio/rjplc-wasm
	rm ../../portfolio/rjplc-wasm/.gitignore

clean:
	rm -rf pkg

portfolio: build-web move-web clean
